ci: try fix

diff --git a/.github/workflows/test-submit.yml b/.github/workflows/test-submit.yml
--- a/.github/workflows/test-submit.yml
+++ b/.github/workflows/test-submit.yml
@@ -21,7 +21,11 @@ jobs:
         run: pnpm --filter extension run zip
 
       - name: Submit to stores
+
         run: |
+          pwd
+          ls -al
+          tree || echo "not found tree"
           pnpm --filter extension exec wxt submit --dry-run \
             --chrome-zip ./apps/extension/.output/*-chrome.zip \
         env:
